server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

missyou:
  security:
    jwt-key: xue666
    token-expired-in: 7200

  order:
    max-sku-limit: 999


